# Generated by Django 3.0.3 on 2020-02-21 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_auto_20200221_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Creation date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="email",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Last modified datetime"
            ),
        ),
    ]
