# Generated by Django 3.0.3 on 2020-02-25 19:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0005_remove_email_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="subject", unique=True
            ),
        ),
    ]
