# Generated by Django 5.2.8 on 2025-11-28 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('emails', '0006_auto_20200225_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name for this category (e.g. 'newsletter', 'announcements').", max_length=100, unique=True, verbose_name='Category Name')),
                ('display_name', models.CharField(help_text='User-friendly display name for the category shown in email preferences.', max_length=200, verbose_name='Display Name')),
                ('description', models.TextField(help_text='User-friendly explanation of what emails users will receive from this category.', verbose_name='Description')),
                ('user_configurable', models.BooleanField(default=True, help_text='If unchecked, users cannot opt out (e.g. for critical announcements.)', verbose_name='User Configurable')),
                ('default_enabled', models.BooleanField(default=True, help_text='Whether users are subscribed to this category by default.', verbose_name='Enabled by Default')),
                ('sort_priority', models.IntegerField(default=0, help_text='Categories with higher priority will be sorted first in user-facing lists (ties broken alphabetically).', verbose_name='Sort Priority')),
                ('is_static', models.BooleanField(default=False, help_text='System-defined category that cannot be deleted', verbose_name='Static Category')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Category',
                'verbose_name_plural': 'Email Categories',
                'ordering': ['-sort_priority', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='email',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Email category for preference filtering. Leave empty to send to all users.', null=True, on_delete=django.db.models.deletion.PROTECT, to='emails.emailcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='emails.emailcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Preference',
                'verbose_name_plural': 'Email Preferences',
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.AddField(
            model_name='email',
            name='recipients_count',
            field=models.IntegerField(default=0, help_text='Number of recipients the email was sent to.', verbose_name='Recipients count'),
        ),
        migrations.AddField(
            model_name='emailcategory',
            name='description_en',
            field=models.TextField(help_text='User-friendly explanation of what emails users will receive from this category.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='emailcategory',
            name='description_fi',
            field=models.TextField(help_text='User-friendly explanation of what emails users will receive from this category.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='emailcategory',
            name='display_name_en',
            field=models.CharField(help_text='User-friendly display name for the category shown in email preferences.', max_length=200, null=True, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='emailcategory',
            name='display_name_fi',
            field=models.CharField(help_text='User-friendly display name for the category shown in email preferences.', max_length=200, null=True, verbose_name='Display Name'),
        ),
    ]
