# Generated by Django 5.2.8 on 2025-11-28 11:50

from django.db import migrations, models

def create_static_categories(apps, schema_editor):
    """
    Create or update static email categories.
    """
    EmailCategory = apps.get_model('emails', 'EmailCategory')

    from emails.models import STATIC_CATEGORIES

    for category_data in STATIC_CATEGORIES.values():
        EmailCategory.objects.update_or_create(
            name=category_data['name'],
            defaults={
                'name': str(category_data['name']),
                'display_name': str(category_data['display_name']),
                'display_name_en': str(category_data['display_name_en']),
                'display_name_fi': str(category_data['display_name_fi']),
                'description': str(category_data['description']),
                'description_en': str(category_data['description_en']),
                'description_fi': str(category_data['description_fi']),
                'user_configurable': category_data['user_configurable'],
                'default_enabled': category_data['default_enabled'],
                'sort_priority': category_data['sort_priority'],
                'is_static': True
            }
        )

def remove_static_categories(apps, schema_editor):
    """
    Reverse migration
    """
    EmailCategory = apps.get_model('emails', 'EmailCategory')
    from emails.models import STATIC_CATEGORIES
    category_names = [data['name'] for data in STATIC_CATEGORIES.values()]
    EmailCategory.objects.filter(name__in=category_names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_emailcategory_email_category_emailpreference'),
    ]

    operations = [
        migrations.RunPython(
            code=create_static_categories,
            reverse_code=remove_static_categories,
        ),
    ]
