# Generated by Django 2.2.2 on 2019-06-18 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, help_text='django expects that we have this field...', max_length=30, null=True, verbose_name='username not used')),
                ('email', models.EmailField(help_text='Your email address will be used for important notifications about your membership', max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.CharField(help_text='This number will also be the one that gets access to the hacklab premises', max_length=255, verbose_name='Mobile phone number')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Automatically set to now when user is create', verbose_name='User creation date')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Last time this user was modified', verbose_name='Last modified datetime')),
                ('last_payment_on', models.DateTimeField(blank=True, help_text='Last datetime this user had a payment transaction happen. TODO: should probably be dynamic', null=True, verbose_name='Last payment')),
                ('marked_for_deletion_on', models.DateTimeField(blank=True, help_text='Filled if the user has marked themself as wanting to end their membership', null=True, verbose_name='Marked for deletion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
