# Generated by Django 2.2.2 on 2019-06-18 17:37

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 6, 18, 17, 37, 4, 643560, tzinfo=utc), verbose_name='Birthday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='municipality',
            field=models.CharField(default='Tampere', max_length=255, verbose_name='Municipality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='nick',
            field=models.CharField(default='-', help_text='IRC / Matric nick or callsign', max_length=255, verbose_name='Nick'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='wants_access_rights',
            field=models.BooleanField(default=True, help_text='Access right grants 24/7 access and costs more than regular membership', verbose_name='I want to have access right'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Your email address will be used for important notifications about your membership', max_length=255, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='django expects that we have this field... TODO: figure out if we can get rid of this completely', max_length=30, null=True, verbose_name='username not used'),
        ),
    ]
