# Generated by Django 2.2.2 on 2019-06-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190626_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reference_number',
            field=models.IntegerField(blank=True, help_text='Remember to always use your unique reference number for membership fee payments', null=True, verbose_name='Reference number of membership fee payments'),
        ),
    ]
