# Generated by Django 3.0.3 on 2020-02-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20200225_1703"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="free form comment field for strange transaction",
                null=True,
            ),
        ),
    ]
