# Generated by Django 3.0.3 on 2020-03-01 16:34

import django.core.validators
from django.db import migrations, models
from users.validators import validate_mxid, validate_phone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_banktransaction_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberservice",
            name="days_maximum",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="How many days of service member can pay at maximum",
            ),
        ),
        migrations.AddField(
            model_name="servicesubscription",
            name="reference_number",
            field=models.BigIntegerField(
                blank=True,
                help_text="Pay for this service with this reference number",
                null=True,
                unique=True,
                verbose_name="Reference number for paying for this service subscription",
            ),
        ),
        migrations.AddField(
            model_name="servicesubscription",
            name="warning_sent",
            field=models.BooleanField(
                default=False,
                help_text="Set to True when a expiration warning message has been sent to user.",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mxid",
            field=models.CharField(
                blank=True,
                help_text="Matrix ID (@user:example.org)",
                max_length=255,
                null=True,
                unique=True,
                validators=[validate_mxid],
                verbose_name="Matrix ID",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                help_text="This number will also be the one that gets access to the hacklab premises. International format (+35840123567).",
                max_length=255,
                null=True,
                validators=[validate_phone],
                verbose_name="Mobile phone number",
            ),
        ),
    ]
