# Generated by Django 3.0.4 on 2020-03-16 14:41

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200310_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mxid',
            field=models.CharField(blank=True, help_text='Matrix ID (@user:example.org)', max_length=255, null=True, unique=True, validators=[users.models.validate_mxid], verbose_name='Matrix ID'),
        ),
    ]
