# Generated by Django 3.0.4 on 2020-03-24 20:07

from django.db import migrations, models
from users.validators import validate_mxid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20200310_1940"),
    ]

    operations = [
        migrations.RemoveField(model_name="nfccard", name="subscription",),
        migrations.AlterField(
            model_name="customuser",
            name="mxid",
            field=models.CharField(
                blank=True,
                help_text="Matrix ID (@user:example.org)",
                max_length=255,
                null=True,
                unique=True,
                validators=[validate_mxid],
                verbose_name="Matrix ID",
            ),
        ),
    ]
