# Generated by Django 3.0.5 on 2020-06-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_memberservice_self_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(choices=[('APPLYING', 'Applying'), ('MEMBER', 'Member'), ('RESIGN_SAVE', 'Resign requested - save account'), ('RESIGN_DELETE', 'Resign requested - delete account'), ('RESIGNED', 'Resigned')], default='MEMBER', help_text='State of this member', max_length=16, verbose_name='Membership state'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Your email address will be used for important notifications about your membership', max_length=255, null=True, unique=True, verbose_name='Email address'),
        ),
    ]
