# Generated by Django 3.0.10 on 2020-09-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_memberservice_access_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Reference number is set by transaction sender and should normally always be used.', max_length=25, null=True, verbose_name='Reference number of transaction'),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Reference number is set by transaction sender and must match this.', max_length=25, null=True, unique=True, verbose_name='Reference number for paying invoice'),
        ),
        migrations.AlterField(
            model_name='servicesubscription',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Pay for this service with this reference number', max_length=25, null=True, unique=True, verbose_name='Reference number for paying for this service subscription'),
        ),
    ]
