# Generated by Django 3.0.10 on 2020-11-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200925_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Reference number is set by transaction sender and should normally always be used.', max_length=25, null=True, verbose_name='Transaction reference'),
        ),
    ]
