# Generated by Django 3.1.7 on 2021-05-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201209_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberservice',
            name='accounting_id',
            field=models.CharField(blank=True, help_text='For accounting export', max_length=20, null=True),
        ),
    ]
