# Generated by Django 4.2.7 on 2023-12-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_memberservice_accounting_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "date",
                    models.DateField(
                        auto_now_add=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Date of this statistics event",
                    ),
                ),
                (
                    "users_total",
                    models.IntegerField(
                        default=0, verbose_name="Total number of users"
                    ),
                ),
                (
                    "users_active",
                    models.IntegerField(default=0, verbose_name="Active users"),
                ),
                (
                    "users_marked_for_deletion",
                    models.IntegerField(
                        default=0, verbose_name="Users pending deletion"
                    ),
                ),
                (
                    "open_membership_applications",
                    models.IntegerField(
                        default=0, verbose_name="Number of open membership applications"
                    ),
                ),
                (
                    "custom_invoices_open",
                    models.IntegerField(
                        default=0, verbose_name="Number of open custom invoices"
                    ),
                ),
                (
                    "custom_invoices_open_sum",
                    models.FloatField(
                        default=0, verbose_name="Total amount of open custom invoices"
                    ),
                ),
                (
                    "service_subscriptions",
                    models.JSONField(
                        default=list,
                        verbose_name="Statistics for service subscriptions. Each service will be its own key with counts for Active, Overdue and Suspended states",
                    ),
                ),
            ],
        ),
    ]
