# Generated by Django 4.1.7 on 2023-12-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_memberservice_accounting_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of this statistics event')),
                ('total_users', models.IntegerField(verbose_name='How many users in total in the system')),
                ('active_users', models.IntegerField(verbose_name='How many active users in in the system')),
                ('open_member_applications', models.IntegerField(verbose_name='Number of open member applications')),
            ],
        ),
    ]
