# Generated by Django 4.2.17 on 2025-02-03 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_statistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Automatically set to now when user is created",
                verbose_name="User creation date",
            ),
        ),
        migrations.AlterField(
            model_name="memberservice",
            name="cost",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Cost of the service",
            ),
        ),
    ]
