# Generated by Django 5.2a1 on 2025-01-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_statistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Automatically set to now when user is created",
                verbose_name="User creation date",
            ),
        ),
    ]