# Generated by Django 4.2.7 on 2023-12-07 17:14

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_statistics_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='statistics',
            managers=[
                ('stats', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='active_users',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='open_member_applications',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='total_users',
        ),
        migrations.AddField(
            model_name='statistics',
            name='users_active',
            field=models.IntegerField(default=0, verbose_name='Active users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='users_total',
            field=models.IntegerField(default=0, verbose_name='Total number of users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True, verbose_name='Date of this statistics event'),
        ),
    ]
