# Generated by Django 4.2.7 on 2023-12-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_statistics_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='id',
        ),
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateField(auto_now_add=True, primary_key=True, serialize=False, unique=True, verbose_name='Date of this statistics event'),
        ),
    ]
