# Generated by Django 5.1.5 on 2025-02-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_banktransaction_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransaction",
            name="archival_reference",
            field=models.CharField(max_length=32, verbose_name="Archival reference"),
        ),
        migrations.AlterUniqueTogether(
            name="banktransaction",
            unique_together={("archival_reference", "date")},
        ),
    ]
