# Generated by Django 5.1.5 on 2025-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_alter_banktransaction_archival_reference_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="banktransaction",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="archival_reference",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Archival reference"
            ),
        ),
    ]
