# Generated by Django 5.1.5 on 2025-03-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_alter_banktransaction_archival_reference_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="banktransaction",
            unique_together=set(),
        ),
    ]
