# Generated by Django 4.2.7 on 2023-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_remove_statistics_id_alter_statistics_date"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="statistics",
            managers=[],
        ),
        migrations.AddField(
            model_name="statistics",
            name="custom_invoices_open",
            field=models.IntegerField(
                default=0, verbose_name="Number of open custom invoices"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statistics",
            name="custom_invoices_open_sum",
            field=models.FloatField(
                default=0, verbose_name="Total amount of open custom invoices"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statistics",
            name="open_membership_applications",
            field=models.IntegerField(
                default=0, verbose_name="Number of open membership applications"
            ),
            preserve_default=False,
        ),
    ]
