# Generated by Django 5.1.9 on 2025-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_alter_banktransaction_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesubscription",
            name="disable_on_expiry",
            field=models.BooleanField(
                default=False,
                help_text="If true, this subscription will be deleted (instead of going overdue) when paid days run out. Automatically set when user self-unsubscribes. Cleared when new payment is received.",
                verbose_name="Disable on expiry",
            ),
        ),
    ]
