# Generated by Django 4.2.7 on 2023-12-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_alter_statistics_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistics",
            name="service_subscriptions",
            field=models.JSONField(
                default=list,
                verbose_name="Statistics for service subscriptions. Each service will be its own key with counts for Active, Overdue and Suspended states",
            ),
        ),
        migrations.AddField(
            model_name="statistics",
            name="users_marked_for_deletion",
            field=models.IntegerField(default=0, verbose_name="Users pending deletion"),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="custom_invoices_open",
            field=models.IntegerField(
                default=0, verbose_name="Number of open custom invoices"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="custom_invoices_open_sum",
            field=models.FloatField(
                default=0, verbose_name="Total amount of open custom invoices"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="open_membership_applications",
            field=models.IntegerField(
                default=0, verbose_name="Number of open membership applications"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="users_active",
            field=models.IntegerField(default=0, verbose_name="Active users"),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="users_total",
            field=models.IntegerField(default=0, verbose_name="Total number of users"),
        ),
    ]
