# Generated by Django 5.1.9 on 2025-10-01 02:44

import users.models.custom_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_alter_banktransaction_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="oidc_sub",
            field=models.CharField(
                default=users.models.custom_user.get_uuid_str,
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
    ]
