# Generated by Django 5.1.12 on 2025-10-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_alter_banktransaction_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberservice",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="User-facing description of what this service provides.",
                null=True,
                verbose_name="Service description",
            ),
        ),
        migrations.AddField(
            model_name="memberservice",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="User-facing description of what this service provides.",
                null=True,
                verbose_name="Service description",
            ),
        ),
        migrations.AddField(
            model_name="memberservice",
            name="description_fi",
            field=models.TextField(
                blank=True,
                help_text="User-facing description of what this service provides.",
                null=True,
                verbose_name="Service description",
            ),
        ),
        migrations.AddField(
            model_name="memberservice",
            name="name_en",
            field=models.CharField(
                help_text="Name of the service",
                max_length=512,
                null=True,
                verbose_name="Service name",
            ),
        ),
        migrations.AddField(
            model_name="memberservice",
            name="name_fi",
            field=models.CharField(
                help_text="Name of the service",
                max_length=512,
                null=True,
                verbose_name="Service name",
            ),
        ),
        migrations.AddField(
            model_name="memberservice",
            name="registration_form_visible",
            field=models.BooleanField(
                default=True,
                help_text="True, if this service should be shown as an option during member registration",
                verbose_name="Show on registration form",
            ),
        ),
    ]
