# Generated by Django 5.1.9 on 2025-10-01 02:45

from django.db import migrations

# Note there is a race condition if you allow objects to be created while this migration is running.
# Objects created after the AddField and before RunPython will have their original uuid’s overwritten.
def populate_oidc_sub(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    for user in CustomUser.objects.all():
        user.oidc_sub = user.email
        user.save(update_fields=["oidc_sub"])

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_customuser_add_oidc_sub_field"),
    ]

    operations = [
        migrations.RunPython(populate_oidc_sub)
    ]
