# Generated by Django 5.1.9 on 2025-10-01 02:45

import users.models.custom_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_customuser_populate_oidc_sub_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="oidc_sub",
            field=models.CharField(
                default=users.models.custom_user.get_uuid_str,
                editable=False,
                max_length=255,
                unique=True,
            ),
        ),
    ]
