# Generated by Django 5.1.13 on 2025-10-29 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A short name for this storage service (e.g. 'Hacklab shelf storage').",
                        max_length=100,
                        unique=True,
                        verbose_name="Storage service name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional longer description of the storage service.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "pending_payment_days",
                    models.PositiveIntegerField(
                        help_text="Number of days a reservation stays pending before expiring if unpaid.",
                        verbose_name="Pending payment period (days)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Automatically set when this storage service is created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this storage service was last modified",
                        verbose_name="Last modified",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageReservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="The date when the reservation starts",
                        verbose_name="Start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="The date when the reservation ends",
                        verbose_name="End date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending"),
                            ("EXPIRED", "Expired"),
                            ("COMPLETED", "Completed"),
                        ],
                        help_text="Current state of the reservation",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_paid_months",
                    models.IntegerField(
                        default=0,
                        help_text="How many months have been paid for this reservation.",
                        verbose_name="Total paid months",
                    ),
                ),
                (
                    "max_duration_months",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum allowed duration for this reservation.",
                        null=True,
                        verbose_name="Maximum duration (months)",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Payment reference number for this reservation",
                        max_length=25,
                        null=True,
                        unique=True,
                        verbose_name="Reference number",
                    ),
                ),
                (
                    "pending_until",
                    models.DateField(
                        blank=True,
                        help_text="Date when the pending reservation expires if unpaid.",
                        null=True,
                        verbose_name="Pending until",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        help_text="Timestamp when the reservation was paid.",
                        verbose_name="Paid at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Automatically set when reservation is created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoragePayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Reference number used for this payment (same as reservation reference)",
                        max_length=25,
                        null=True,
                        verbose_name="Reference number",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount of money paid for this reservation.",
                        max_digits=7,
                        verbose_name="Amount (€)",
                    ),
                ),
                (
                    "months",
                    models.IntegerField(
                        help_text="How many months of storage this payment covers.",
                        verbose_name="Paid months",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Automatically set when the payment record is created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when payment was received",
                        null=True,
                        verbose_name="Payment date",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="True if payment was matched with a bank transaction (Nordigen).",
                        verbose_name="Verified",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.storagereservation",
                        verbose_name="Related reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageUnit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name or identifier of the unit",
                        max_length=50,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_disabled",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this unit cannot be reserved (e.g. blocked or permanently occupied).",
                        verbose_name="Disabled",
                    ),
                ),
                (
                    "price_per_month",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly price for renting this storage unit",
                        max_digits=7,
                        verbose_name="Price per month",
                    ),
                ),
                (
                    "max_rental_months",
                    models.PositiveIntegerField(
                        help_text="Maximum allowed rental duration for this storage unit",
                        verbose_name="Maximum rental duration (months)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description for this storage unit (e.g. dimensions, location details).",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "show_name_publicly",
                    models.BooleanField(
                        default=True,
                        help_text="Determines if the name of the renter will be visible for all users",
                        verbose_name="Show renter’s name publicly",
                    ),
                ),
                (
                    "allow_self_subscription",
                    models.BooleanField(
                        default=True,
                        help_text="If true, users can reserve this unit themselves without admin approval.",
                        verbose_name="Allow self-subscription",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Automatically set when this storage unit is created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this unit was last modified",
                        verbose_name="Last modified",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.storageservice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="storagereservation",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="storage.storageunit"
            ),
        ),
    ]
