# Generated by Django 5.1.13 on 2025-11-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagereservation",
            name="paid_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the reservation was paid.",
                null=True,
                verbose_name="Paid at",
            ),
        ),
    ]
