# Generated by Django 5.1.13 on 2025-11-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_alter_storagereservation_paid_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storagepayment",
            name="verified",
        ),
        migrations.RemoveField(
            model_name="storageunit",
            name="show_name_publicly",
        ),
    ]
