# Generated by Django 3.0.3 on 2020-03-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200307_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessdevice',
            name='deviceid',
            field=models.CharField(help_text='used to know which device this was', max_length=255, unique=True, verbose_name='device id'),
        ),
    ]
