# Generated by Django 3.0.4 on 2020-03-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_auto_20200324_2007"),
        ("api", "0003_auto_20200310_1940"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceAccessLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Automatically set to now when created",
                        verbose_name="Date of this entry",
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(
                        help_text="Was the access granted", verbose_name="Granted"
                    ),
                ),
                (
                    "payload",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="NFC card id or phone number, or other field like that",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.AccessDevice",
                        verbose_name="Device this event came from",
                    ),
                ),
                (
                    "nfccard",
                    models.ForeignKey(
                        help_text="NFC card this was mapped to, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.NFCCard",
                        verbose_name="NFC card",
                    ),
                ),
            ],
        ),
    ]
