# Generated by Django 3.0.11 on 2020-11-30 23:23

from drfx import config
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(config.AUTH_USER_MODEL),
        ('api', '0004_deviceaccesslogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceaccesslogentry',
            name='claimed_by',
            field=models.ForeignKey(help_text='Who claimed this entry', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=config.AUTH_USER_MODEL, verbose_name='User who claimed this'),
        ),
    ]
