# Generated by Django 3.0.7 on 2020-12-01 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_deviceaccesslogentry_claimed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceaccesslogentry',
            name='claimed_by',
            field=models.ForeignKey(help_text='Who claimed this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Claimed by'),
        ),
    ]
