# Generated by Django 5.1.5 on 2025-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20201201_1558"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceaccesslogentry",
            name="method",
            field=models.CharField(
                default="",
                help_text="Method of device access",
                max_length=64,
                verbose_name="Method",
            ),
        ),
    ]
