# Generated by Django 5.1.7 on 2025-03-27 12:31

from django.db import migrations


class Migration(migrations.Migration):
    """
    Update the length of the `jti` column in the `oauth2_provider_idtoken` table 
    from CHAR(32) to CHAR(36).

    In Django versions < 5.0, UUIDFields were stored as 32-character hex strings.
    Starting from Django 5.0, UUIDFields are stored as 36-character dashed strings
    (the canonical string representation of UUIDs).

    The `jti` field in django-oauth-toolkit uses a UUIDField and now requires a
    longer column to avoid DataError exceptions when saving tokens.

    See also: 
    https://docs.djangoproject.com/en/5.1/releases/5.0/#migrating-uuidfield
    https://www.albertyw.com/note/django-5-mariadb-uuidfield
    """

    dependencies = [
        ("oauth2_provider", "0012_add_token_checksum"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE oauth2_provider_idtoken MODIFY COLUMN jti CHAR(36) NOT NULL;",
            reverse_sql="ALTER TABLE oauth2_provider_idtoken MODIFY COLUMN jti CHAR(32) NOT NULL;",
        )
    ]
