# Generated by Django 4.1.2 on 2022-10-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_id",
                    models.CharField(max_length=1024, verbose_name="Nordigen API id"),
                ),
                (
                    "api_key",
                    models.CharField(max_length=1024, verbose_name="Nordigen API key"),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("FI", "FI")],
                        max_length=2,
                        verbose_name="Nordigen API country",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        choices=[
                            ("Bank Norwegian", "Bank Norwegian"),
                            ("Danske Bank Business", "Danske Bank Business"),
                            ("Danske Bank Private", "Danske Bank Private"),
                            ("Handelsbanken Corporate", "Handelsbanken Corporate"),
                            ("Handelsbanken Private", "Handelsbanken Private"),
                            ("N26 Bank", "N26 Bank"),
                            ("Nordea Business", "Nordea Business"),
                            ("Nordea Corporate", "Nordea Corporate"),
                            ("Nordea Personal", "Nordea Personal"),
                            ("Oma Säästöpankki", "Oma Säästöpankki"),
                            ("OP Financial Group", "OP Financial Group"),
                            ("PayPal", "PayPal"),
                            ("POP Pankki", "POP Pankki"),
                            ("Resurs Bank", "Resurs Bank"),
                            ("Revolut", "Revolut"),
                            ("S-Pankki", "S-Pankki"),
                            ("SEB Kort Bank AB", "SEB Kort Bank AB"),
                            (
                                "SEB Kort Bank AB Corporate",
                                "SEB Kort Bank AB Corporate",
                            ),
                            ("Stripe", "Stripe"),
                            ("Säästöpankki", "Säästöpankki"),
                            ("Wise", "Wise"),
                            ("Ålandsbanken", "Ålandsbanken"),
                        ],
                        max_length=256,
                        verbose_name="Nordigen API Institution",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Automatically set to now",
                        verbose_name="Creation date",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Automatically updated",
                        verbose_name="Last modified datetime",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Requisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        verbose_name="Nonce for verification purposes",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        verbose_name="Nordigen URL to handle the requisition",
                    ),
                ),
                (
                    "requisition_id",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        verbose_name="Nordigen Requisition id",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="How long this requisition id is valid untill",
                    ),
                ),
                (
                    "ready",
                    models.BooleanField(
                        default=False,
                        verbose_name="Is the requisition valid (user has completed the operation required)",
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(
                        default=False, verbose_name="Deprecated requisition"
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nordigenautomation.config",
                    ),
                ),
            ],
        ),
    ]
