# Generated by Django 4.1.2 on 2022-10-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nordigenautomation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="country",
            field=models.CharField(
                choices=[("FI", "FI"), ("XX", "XX")],
                max_length=2,
                verbose_name="Nordigen API country",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="institution",
            field=models.CharField(
                choices=[
                    ("Bank Norwegian", "Bank Norwegian"),
                    ("Danske Bank Business", "Danske Bank Business"),
                    ("Danske Bank Private", "Danske Bank Private"),
                    ("Handelsbanken Corporate", "Handelsbanken Corporate"),
                    ("Handelsbanken Private", "Handelsbanken Private"),
                    ("N26 Bank", "N26 Bank"),
                    ("Nordea Business", "Nordea Business"),
                    ("Nordea Corporate", "Nordea Corporate"),
                    ("Nordea Personal", "Nordea Personal"),
                    ("Oma Säästöpankki", "Oma Säästöpankki"),
                    ("OP Financial Group", "OP Financial Group"),
                    ("PayPal", "PayPal"),
                    ("POP Pankki", "POP Pankki"),
                    ("Resurs Bank", "Resurs Bank"),
                    ("Revolut", "Revolut"),
                    ("S-Pankki", "S-Pankki"),
                    ("SEB Kort Bank AB", "SEB Kort Bank AB"),
                    ("SEB Kort Bank AB Corporate", "SEB Kort Bank AB Corporate"),
                    ("Stripe", "Stripe"),
                    ("Säästöpankki", "Säästöpankki"),
                    ("Wise", "Wise"),
                    ("Ålandsbanken", "Ålandsbanken"),
                    ("Sandbox Finance", "Sandbox Finance"),
                ],
                max_length=256,
                verbose_name="Nordigen API Institution",
            ),
        ),
    ]
