# Generated by Django 5.1.12 on 2025-09-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nordigenautomation", "0002_alter_config_country_alter_config_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="valid_until",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="How long this requisition id is valid until",
            ),
        ),
    ]
