# run tox in master and pr's
name: "CI tox"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pipenv
        run: pip install pipenv
      - name: run tox
        run: |
          pipenv sync --dev
          pipenv run tox
          pipenv run coveralls